<section class="org-form-section">
    <div class="org-section-title"><div class="org-section-icon"><i class="fa-solid fa-sitemap"></i></div><div><h2>Vínculo hierárquico</h2><p>Selecione a posição oficial ocupada pelo funcionário.</p></div></div>
    <div class="org-callout"><i class="fa-solid fa-circle-info"></i><div>Empresa e Unidade são confirmadas pela linha de Hierarquia selecionada. O sistema não permitirá combinações incompatíveis.</div></div>
    <div class="org-form-grid">
        <div class="org-field org-col-6"><label for="empresa_id">Empresa *</label><select name="empresa_id" id="empresa_id" class="form-select" required><option value="">Selecione</option><?php foreach ($empresas as $empresa): ?><option value="<?= (int)$empresa['id'] ?>" <?= (string)($dados['empresa_id'] ?? '') === (string)$empresa['id'] ? 'selected' : '' ?>><?= htmlspecialchars($empresa['nome_fantasia'] ?: $empresa['razao_social']) ?></option><?php endforeach; ?></select></div>
        <div class="org-field org-col-6"><label for="unidade_id">Unidade *</label><select name="unidade_id" id="unidade_id" class="form-select" required><option value="">Selecione</option><?php foreach ($unidades as $unidade): ?><option value="<?= (int)$unidade['id'] ?>" data-empresa="<?= (int)$unidade['empresa_id'] ?>" <?= (string)($dados['unidade_id'] ?? '') === (string)$unidade['id'] ? 'selected' : '' ?>><?= htmlspecialchars($unidade['nome']) ?></option><?php endforeach; ?></select></div>
        <div class="org-field org-col-12"><label for="hierarquia_id">Setor / Cargo *</label><select name="hierarquia_id" id="hierarquia_id" class="form-select" required><option value="">Selecione</option><?php foreach ($hierarquias as $hierarquia): ?><option value="<?= (int)$hierarquia['id'] ?>" data-empresa="<?= (int)$hierarquia['empresa_id'] ?>" data-unidade="<?= (int)$hierarquia['unidade_id'] ?>" <?= (string)($dados['hierarquia_id'] ?? '') === (string)$hierarquia['id'] ? 'selected' : '' ?>><?= htmlspecialchars(($hierarquia['setor_nome'] ?? '-') . ' — ' . ($hierarquia['cargo_nome'] ?? '-')) ?></option><?php endforeach; ?></select><small>O funcionário será associado à hierarquia oficial da unidade.</small></div>
    </div>
</section>
<section class="org-form-section">
    <div class="org-section-title"><div class="org-section-icon"><i class="fa-regular fa-id-card"></i></div><div><h2>Dados do funcionário</h2><p>Informe os dados cadastrais disponíveis.</p></div></div>
    <div class="org-form-grid">
        <div class="org-field org-col-8"><label for="nome">Nome completo *</label><input type="text" name="nome" id="nome" class="form-control" maxlength="180" required value="<?= htmlspecialchars((string)($dados['nome'] ?? '')) ?>"></div>
        <div class="org-field org-col-4"><label for="data_admissao">Data de admissão</label><input type="date" name="data_admissao" id="data_admissao" class="form-control" value="<?= htmlspecialchars((string)($dados['data_admissao'] ?? '')) ?>"></div>
        <div class="org-field org-col-3"><label for="matricula">Matrícula</label><input type="text" name="matricula" id="matricula" class="form-control" maxlength="50" value="<?= htmlspecialchars((string)($dados['matricula'] ?? '')) ?>"></div>
        <div class="org-field org-col-3"><label for="cpf">CPF</label><input type="text" name="cpf" id="cpf" class="form-control" maxlength="20" value="<?= htmlspecialchars((string)($dados['cpf'] ?? '')) ?>"></div>
        <div class="org-field org-col-3"><label for="codigo">Código interno</label><input type="text" name="codigo" id="codigo" class="form-control" maxlength="30" value="<?= htmlspecialchars((string)($dados['codigo'] ?? '')) ?>"></div>
        <div class="org-field org-col-3"><label for="codigo_externo">Código externo</label><input type="text" name="codigo_externo" id="codigo_externo" class="form-control" maxlength="80" value="<?= htmlspecialchars((string)($dados['codigo_externo'] ?? '')) ?>"></div>
        <div class="org-field org-col-12"><label for="observacoes">Observações</label><textarea name="observacoes" id="observacoes" class="form-control" rows="5"><?= htmlspecialchars((string)($dados['observacoes'] ?? '')) ?></textarea></div>
    </div>
</section>
<script>
document.addEventListener('DOMContentLoaded',function(){const empresa=document.getElementById('empresa_id'),unidade=document.getElementById('unidade_id'),hierarquia=document.getElementById('hierarquia_id');function atualizar(){const empresaId=empresa?.value||'',unidadeId=unidade?.value||'';Array.from(unidade?.options||[]).forEach(function(o){if(!o.value)return;o.hidden=empresaId!==''&&o.dataset.empresa!==empresaId;if(o.hidden&&o.selected)unidade.value='';});Array.from(hierarquia?.options||[]).forEach(function(o){if(!o.value)return;o.hidden=(empresaId!==''&&o.dataset.empresa!==empresaId)||(unidadeId!==''&&o.dataset.unidade!==unidadeId);if(o.hidden&&o.selected)hierarquia.value='';});}empresa?.addEventListener('change',function(){if(unidade)unidade.value='';if(hierarquia)hierarquia.value='';atualizar();});unidade?.addEventListener('change',function(){if(hierarquia)hierarquia.value='';atualizar();});atualizar();});
</script>
